# Generated by Django 3.2.7 on 2021-09-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bioactive_compound', models.CharField(max_length=200, null=True)),
                ('uses', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
